language: node_js
node_js:
  - '8'
  - '6'
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  only:
    - master
jobs:
  include:
    - stage: Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
