---
name: Staging
on:
  pull_request:
    branches: [prod]
jobs:
  prepare-and-run-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
